In [2]:
import numpy as np
# vectorization: fixing the looping problem
arr = np.array([1, 2, 3, 4, 5])
result = arr ** 2  # Vectorized operation
print(result)  # Output: [1 4 9 16 25]

[ 1  4  9 16 25]


In [3]:
#broadcasting: scaling arrays without extra momery
result + 10 #here 10 is scalar
result

array([ 1,  4,  9, 16, 25])

In [4]:
#broadcasting with two arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([20, 30, 40])
result = arr1 + arr2 #numpy allows two arrays to perform element wise adition as the have same shape
result

array([21, 32, 43])

In [7]:
#broadcasting 2D array and 1D array
arr1 = np.array([[1, 2, 3],[4, 5, 6]])
arr2 = np.array([7, 8, 9])
result = arr1 + arr2 #broadcasting array 1 across array2
result

array([[ 8, 10, 12],
       [11, 13, 15]])

Example: Normalizing Data Using Broadcasting
Imagine you have a dataset where each row represents a sample and each column represents a feature. You can normalize the data by subtracting the mean of each column and dividing by the standard deviation.

In [10]:
# Simulating a dataset (5 samples, 3 features)
data = np.array([[10, 20, 30],
                 [15, 25, 35],
                 [20, 30, 40],
                 [25, 35, 45],
                 [30, 40, 50]])

# Calculating mean and standard deviation for each feature (column)
mean = data.mean(axis=0)
std = data.std(axis=0)

# Normalizing the data using broadcasting
normalized_data = (data - mean) / std

print(normalized_data)

[[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]


In [16]:
#problem 1 Given a 2D array A of shape (3, 4) and a 1D array b of shape (4,), add b to each row of A using broadcasting.
import numpy as np
A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])
b = np.array([1, 0, -1, 2])
result = A+b
result

array([[ 2,  2,  2,  6],
       [ 6,  6,  6, 10],
       [10, 10, 10, 14]])

In [17]:
#problem 2: Multiply a 1D column vector with each column of a 2D matrix using broadcasting.
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
v = np.array([[1], [2], [3]])  # Shape: (3,1)
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
v

array([[1],
       [2],
       [3]])

In [20]:
product = A*v
product

array([[ 1,  2,  3],
       [ 8, 10, 12],
       [21, 24, 27]])

In [26]:
#problem 3 Given a 2D array, subtract the mean of each row from the row using broadcasting.
A = np.array([[5, 10, 15],
              [2, 4, 6]])
row_mean = np.mean(A, axis=1, keepdims=True)
row_mean

array([[10.],
       [ 4.]])

In [27]:
result = A-row_mean
result

array([[-5.,  0.,  5.],
       [-2.,  0.,  2.]])

In [28]:
#problem 4: Simulate a 3D RGB image of shape (2, 2, 3) and add a specific value to each color channel (R, G, B) using broadcasting.
image = np.array([[[10, 20, 30],
                   [40, 50, 60]],
                  
                  [[70, 80, 90],
                   [100, 110, 120]]])  # Shape: (2, 2, 3)

add_values = np.array([1, -1, 5])  # Add to RGB
result = image+add_values
result

array([[[ 11,  19,  35],
        [ 41,  49,  65]],

       [[ 71,  79,  95],
        [101, 109, 125]]])

In [37]:
#problem 5: Given a 2D array, subtract the mean of each column and divide by its standard deviation using broadcasting.
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
mean = np.mean(A, axis=0, keepdims=True)
mean

array([[4., 5., 6.]])

In [38]:
std = np.std(A, axis=0, keepdims=True)
std

array([[2.44948974, 2.44948974, 2.44948974]])

In [39]:
result = (A-mean)/std
result

array([[-1.22474487, -1.22474487, -1.22474487],
       [ 0.        ,  0.        ,  0.        ],
       [ 1.22474487,  1.22474487,  1.22474487]])