In [1]:
import numpy as np


In [2]:
!pip install numpy # to install numpy

In [3]:
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

we did'nt creat arrays just from list there is so many other particular ways to create arrays

In [4]:
# creating arrays from scratch
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
np.full((4, 6), 8)

array([[8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8]])

In [8]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:
np.arange(1, 12, 2) # like range 

array([ 1,  3,  5,  7,  9, 11])

In [11]:
np.linspace(1, 100, 5) # equally spaced array of 5 elements

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [15]:
myarr = np.array([[10, 20, 30], [40, 50, 60], [2, 3, 4], [4, 5, 6]])
myarr

array([[10, 20, 30],
       [40, 50, 60],
       [ 2,  3,  4],
       [ 4,  5,  6]])

In [16]:
myarr.shape # gives rows and coloumns

(4, 3)

In [17]:
myarr.size # total number of elements 4*3 = 12

12

In [18]:
myarr.ndim # show dimension means 2D

2

In [19]:
myarr.dtype # how numpy store your numbers 

dtype('int32')

changing the data type:
Can we change the data type of numpy? the answer is yes.

In [20]:
myarr = np.array([[10, 20, 30], [40, 50, 60], [2, 3, 4], [4, 5, 6]], dtype='float32') #gives 32 bit floating numbers
myarr

array([[10., 20., 30.],
       [40., 50., 60.],
       [ 2.,  3.,  4.],
       [ 4.,  5.,  6.]], dtype=float32)

In [21]:
myarr

array([[10., 20., 30.],
       [40., 50., 60.],
       [ 2.,  3.,  4.],
       [ 4.,  5.,  6.]], dtype=float32)

In [22]:
n = myarr.astype('float64') # it will convert myarr which is float32 into float64

In [23]:
n.dtype

dtype('float64')

In [24]:
myarr.dtype #but myarr main array is still float32

dtype('float32')

Reshaping and flattening arrays

In [28]:
myarr = np.array([[10, 20, 30], [40, 50, 60], [2, 3, 4], [4, 5, 6]])
myarr

array([[10, 20, 30],
       [40, 50, 60],
       [ 2,  3,  4],
       [ 4,  5,  6]])

In [29]:
myarr.shape

(4, 3)

In [30]:
reshaped = myarr.reshape((3, 4))# it will change the shape in 3 rows and 4 coloumns

In [31]:
reshaped

array([[10, 20, 30, 40],
       [50, 60,  2,  3],
       [ 4,  4,  5,  6]])

In [32]:
myarr.reshape((2, 6))

array([[10, 20, 30, 40, 50, 60],
       [ 2,  3,  4,  4,  5,  6]])

In [33]:
# myarr.reshape((2, 10)) will give error bcz no of elements should be same 2*10 is 20 but myarr has no of elements 12

In [35]:
myarr.flatten() # it will convert 2D into 1D

array([10, 20, 30, 40, 50, 60,  2,  3,  4,  4,  5,  6])

In [38]:
# problem 1 Use np.arange() to create a 3x3 NumPy array with values from 1 to 9.
arr = np.arange(1, 10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
reshape = arr.reshape((3, 3))
reshape

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
# Problem 2: Create an Array with Evenly Spaced Floats
arr2 = np.linspace(0, 1, 6)
arr2

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [42]:
# Problem 3: Create a 2D Array of Random Floats
# Create a 4x2 NumPy array with random float numbers between 0 and 1.
import numpy as np

array = np.random.rand(4, 2)
print(array)



[[0.50708928 0.13978718]
 [0.61270939 0.28285401]
 [0.13040264 0.31784316]
 [0.25387392 0.75028697]]


In [44]:
# problem 4 Create a 1D NumPy array with the values [1, 2, 3, 4], but make sure the data type is float.
arr4 = np.array([1, 2, 3, 4], 'float')
arr4

array([1., 2., 3., 4.])

In [48]:
# problem 5 Create a 1D NumPy array from 0 to 11 and reshape it into a 3x4 matrix.
arr5 = np.arange(0, 12)
reshape = arr5.reshape(3, 4)
reshape

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])