In [1]:
import numpy as np
arr = np.array([22, 44, 1, 2])
arr

array([22, 44,  1,  2])

In [3]:
arr.astype("float32") #change the data type into float

array([22., 44.,  1.,  2.], dtype=float32)

In [6]:
arr2 = np.array([22, 3, 4, 5], dtype="float32")
arr2

array([22.,  3.,  4.,  5.], dtype=float32)

In [7]:
arr2.astype("int32")

array([22,  3,  4,  5])

In [8]:
arr2.nbytes

16

In [9]:
arr.nbytes

16

In [10]:
#both arrays arr and arr2 uses 16bytes because they have 4 elements each and both 4 bytes per elements

In [11]:
arr_int64 = np.array([1, 2, 3], dtype=np.int64)
arr_int32 = np.array([1, 2, 3], dtype=np.int32)

print(arr_int64.nbytes)  # Output: 24 bytes (3 elements * 8 bytes each)
print(arr_int32.nbytes)  # Output: 12 bytes (3 elements * 4 bytes each)

24
12


In [12]:
# string data type
arr = np.array(['apple', 'banana', 'cherry'], dtype='U10')  # Unicode string array
arr

array(['apple', 'banana', 'cherry'], dtype='<U10')

In [13]:
#complex numbers
arr = np.array([1 + 2j, 3 + 4j, 5 + 6j], dtype='complex128')
arr

array([1.+2.j, 3.+4.j, 5.+6.j])

In [14]:
#object data type
arr = np.array([{'a': 1}, [1, 2, 3], 'hello'], dtype=object)
arr

array([{'a': 1}, list([1, 2, 3]), 'hello'], dtype=object)