In [6]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [7]:
flat = arr.flatten()# to make it 1D
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [8]:
flat[0] #indexing is same like python list

1

In [9]:
flat[1]

2

In [11]:
flat[3: 6]

array([4, 5, 6])

In [12]:
flat[:5] #same as flat[0:5]

array([1, 2, 3, 4, 5])

In [14]:
flat[3:]# same as flat[3:13]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [15]:
flat[3:13]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [16]:
flat[::2] # gives every second element of list

array([ 1,  3,  5,  7,  9, 11])

slicing returns a view, not a copy! changes affect the original array but in python list changes does not effect the original list

In [17]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [20]:
b = flat[3: 7]
b

array([4, 5, 6, 7])

In [22]:
b[0] = 4444
b

array([4444,    5,    6,    7])

In [23]:
flat # changes also occur in original array

array([   1,    2,    3, 4444,    5,    6,    7,    8,    9,   10,   11,
         12])

In [25]:
b = flat[3:7].copy() # this is not slicing because we are using copy method
b

array([4444,    5,    6,    7])

In [26]:
# fancy indexing 
arr = np.array([1, 54, 23, 55, 2, 3, 34, 5, 6])
arr[[1, 4, 6]] # give elements of just these indices inside the list

array([54,  2, 34])

In [28]:
#Boolean masking
arr = np.array([1, 54, 23, 55, 2, 3, 34, 5, 6])
arr[arr>3] #condition: values in array greater than 3

array([54, 55, 34])

In [30]:
arr[arr>23] #condition: values in array greater than 23

array([54, 55, 34])

In [31]:
# this is a very powerfull way to filter large data set

practice problems 

In [36]:
# problem 1 Create a 3×3 array filled with random numbers and print its shape.
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr.shape

(3, 3)

In [37]:
# problem 2 Convert an array of floats [1.1, 2.2, 3.3] into integers.
arr1 = np.array([1.1, 2.2, 3.3],)
arr1

array([1.1, 2.2, 3.3])

In [39]:
arr1.astype(np.int32)

array([1, 2, 3])

In [42]:
#problem 3 Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6].
arr2 = np.array([1, 2, 3, 4, 5, 6])
idx = [1, 3, 5,]
arr2[idx]

array([2, 4, 6])

In [49]:
# problem 4 Reshape a 1D array of size 9 into a 3×3 matrix.
arr4 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr.reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
#problem 5 Use boolean masking to filter numbers greater than 50 in an array.
arr5 = np.array([1, 14, 16, 55, 66, 70, 99])
arr5[arr5>50]

array([55, 66, 70, 99])

In [54]:
# problem 6 Create a 5×5 identity matrix using NumPy.
arr6 = np.eye(5)
arr6

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [65]:
# problem 7 Generate a 1D NumPy array of 20 random integers between 10 and 99, and count how many are divisible by 3.
arr7 = np.arange(10, 100)
arr20 = arr7[:20]
div_by_3 = arr20%3 ==0
count = np.sum(div_by_3)
print(arr20)
print(arr20[div_by_3])
print(count)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
[12 15 18 21 24 27]
6
