In [1]:
import numpy as np
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [2]:
np.mean(arr)# to find the mean

2.5

In [4]:
np.max(arr) #to find the maximum value

4

In [5]:
np.min(arr) # to find the minimum value

1

In [6]:
np.std(arr) #to find standard deviation

1.118033988749895

In [7]:
np.var(arr) # to find the variance

1.25

In [8]:
np.sum(arr)# to find sum of all elements

10

In [9]:
np.prod(arr)#to find the product of all elemnets

24

In [10]:
np.median(arr)

2.5

In [11]:
np.percentile(arr, 0)

1.0

In [12]:
np.argmin(arr) #which index has smallest element

0

In [13]:
np.argmax(arr)# which index has largest element

3

In [14]:
arr1 = np.array([1, 2, 4, 5, 2, 4, 3])
np.unique(arr1) # gives uniques elements no duplicate

array([1, 2, 3, 4, 5])

In [17]:
arr

array([1, 2, 3, 4])

In [15]:
np.diff(arr) #difference between all elements

array([1, 1, 1])

In [16]:
np.cumsum(arr) #cumulative sum(1, 1+2=3, 3+3=6, 6+4=10)

array([ 1,  3,  6, 10])

In [18]:
np.linspace(1, 10, 5)#create array of evenly spaced numbers

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [19]:
np.log(arr) # to find the log 

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [20]:
np.exp(arr)# to find the exponential

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [5]:
#problem 1: Given a 2D array, compute the sum and mean of each row.
import numpy as np
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
sum = np.sum(A, axis=1,)
print(sum)
mean = np.mean(A, axis=1)
print(mean)

[ 6 15 24]
[2. 5. 8.]


In [7]:
#problem 2:Given an array, compute the element-wise exponential and square root of the elements. 
arr = np.array([1, 4, 9, 16])
exponential = np.exp(arr)
print(exponential)
square = np.sqrt(arr)
print(square)

[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
[1. 2. 3. 4.]


In [8]:
#problem 3: Cumulative Sum and Product
arr = np.array([1, 2, 3, 4])
cumulative_sum = np.cumsum(arr)
print(cumulative_sum)
cumulative_product = np.cumprod(arr)
print(cumulative_product)

[ 1  3  6 10]
[ 1  2  6 24]


In [9]:
#problem 4: Given angles in degrees, compute the sine of each angle.
import numpy as np

angles_deg = np.array([0, 30, 45, 60, 90])

# Step 1: Convert degrees to radians
angles_rad = np.radians(angles_deg)

# Step 2: Compute the sine of each angle
sine_values = np.sin(angles_rad)
print(angles_rad)
print(sine_values)


[0.         0.52359878 0.78539816 1.04719755 1.57079633]
[0.         0.5        0.70710678 0.8660254  1.        ]


#problem 5: Given a 1D NumPy array of test scores, perform z-score normalization — that is, subtract the mean and divide by the standard deviation.
Z-score normalization (also called standardization) is a way to transform data so that:
1-The mean becomes 0
2-The standard deviation becomes 1
formula:
z-score =(original value - mean)/ standard deviation

In [12]:
import numpy as np
scores = np.array([55, 72, 89, 65, 78, 90, 62])
mean = np.mean(scores)
std = np.std(scores)
z_score = (scores - mean)/std
z_score


array([-1.44913767, -0.08050765,  1.28812238, -0.64406119,  0.40253824,
        1.36863003, -0.88558413])