In [2]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
arr[0] # it will gives the first row

array([1, 2, 3])

In [4]:
arr[1] #will give second row

array([4, 5, 6])

In [5]:
arr[2] # will give 3rd row

array([7, 8, 9])

In [6]:
np.sum(arr, axis = 0) # sum the 1st, 2nd, 3rd elements of row1 row2 and row3(1+4+7=12), (2++5+8=15), (3+6+9=18)

array([12, 15, 18])

In [8]:
np.sum(arr, axis=1)# coloumns wise sum (1+2+3=6), (4+5+6= 15), (7+8+9 = 24)

array([ 6, 15, 24])

In [9]:
arr[0][1]# means element at index one of row 1

2

In [11]:
arr[0, 1] # take index 0 row and index 1 row 

2

In [13]:
arr[0:2, 1:3] # overlapping part of rows with index 0,1 and coloumns with index 1, 2 

array([[2, 3],
       [5, 6]])

In [14]:
# indexing in 3D
arr3D = np.array([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]]])
arr3D

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [15]:
arr3D.shape# 2 depths 2 rows and 3 coloumns

(2, 2, 3)

In [17]:
arr3D[0] # it will print the first particular part of array 3D

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
arr3D[0, 1, 2]#  0 shows particular sheet row with index 1 and coloumn with index 2 

6

In [22]:
arr3D[:,0, :] # get the row from both the sheets

array([[1, 2, 3],
       [7, 8, 9]])

In [23]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:

first_coloumn = arr[:, 0]
first_coloumn

array([1, 4, 7])

In [27]:
second_coloumn = arr[:, 1]
second_coloumn

array([2, 5, 8])

In [28]:
third_coloumn = arr[:, 2]
third_coloumn

array([3, 6, 9])

In [29]:
first_row = arr[0, :]
first_row

array([1, 2, 3])

In [31]:
second_row = arr[1, :]
second_row

array([4, 5, 6])

In [32]:
arr3D #now see rows and coloumns for 3D

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [33]:
first_row = arr3D[:, 0, :] #get the first row from each sheet
first_row

array([[1, 2, 3],
       [7, 8, 9]])

In [34]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
#changing data along axis
arr[:, 1] = 0
arr

array([[1, 0, 3],
       [4, 0, 6],
       [7, 0, 9]])

In [2]:
# problem 1: Create an 8x8 NumPy array with a checkerboard pattern of 0s and 1s (like a chessboard), starting with 0.
import numpy as np
checkboard = np.zeros((8, 8),dtype = int)
checkboard

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [3]:
checkboard[1::2, ::2] = 1 # 1::2 pics odd rows and ::2 pics even coloumns
checkboard

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [4]:
checkboard[::2, 1::2] = 1 # ::2 pics even rows and 1::2 pics odd coloumns
checkboard

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [6]:
# problem 2: Create a 5x5 array with all 1s on the border and 0s inside.
arr2 = np.ones((5, 5), dtype = int)
arr2

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [13]:
arr2[1:4] = 0
arr2

array([[1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1]])

In [10]:
arr2[:, 0] = 1
arr2

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 1, 1, 1, 1]])

In [12]:
arr2[:,4] = 1
arr2

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])