In [10]:
# by using python lists
import numpy as np
import time
size = 1_000_000_0
l1 = list(range(size))
l2 = list(range(size))
start = time.time()
result = [x+y for x,y in zip(l1, l2)] #list comprehension 
end = time.time()
print(result[0:10])
print(end - start)



[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
1.3564512729644775


In [11]:
#  by using numpy array
import numpy as np
import time
size = 1_000_000_0
l1 =np.array(list(range(size)))
l2 = np.array(list(range(size)))
start = time.time()
result = l1 + l2
end = time.time()
print(result[0:10])
print(end - start) # works in very less time it has more speed than python list



[ 0  2  4  6  8 10 12 14 16 18]
0.23732447624206543


In [12]:
# how to make numpy array?
#numpy can by using python list
np.array([1, 2, 3, 4, 5]) # it will give us a numpy array

array([1, 2, 3, 4, 5])

In [13]:
np.array([1, 2, 3, 4, 5, "hadia"]) # it gives array but data type is unicode string so array should be numbers 

array(['1', '2', '3', '4', '5', 'hadia'], dtype='<U11')

In [14]:
np.array([[1, 2, 3], [4, 5, 6]]) # 2D array

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
#np.array([[1, 2, 3], [4, 5, 6, 7, 8]]) it will give arror no of rows should be equal in both list

In [16]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
type(arr)

numpy.ndarray

In [17]:
arr.shape # (2, #) means 2 rows and 3 coloumns

(2, 3)

why using numpy arrays because it highly optimized
backend is hihly optimized c language
faster for nummerical computing
numpy overcome the slowness of python list

In [18]:
# memory efficency numpy VS lists
import sys

list_data = list(range(1000))
numpy_data = np.array(list_data)

print("Python list size:", sys.getsizeof(list_data) * len(list_data), "bytes")
print("NumPy array size:", numpy_data.nbytes, "bytes")

Python list size: 8056000 bytes
NumPy array size: 4000 bytes


In [22]:
# vectorization - no more loops
import time
list1 = [1, 2, 3, 4]
start = time.time()
list_square = [ x**2 for x in list1]
end = time.time()
print(list_square)
print(end - start)

[1, 4, 9, 16]
0.000942230224609375


In [21]:
import time
arra1 = np.array([1, 2, 3, 4])
start = time.time()
# vectorized
list_square = arra1 **2 # no need of for loop
end = time.time()
print(list_square)
print(end - start)

[ 1  4  9 16]
0.0071947574615478516


In [26]:
#Exercises for Practice
#Create a NumPy array with values from 10 to 100 and print its shape.
array = np.arange(10, 101)
print(array)
array.shape

[ 10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 100]


(91,)

In [35]:
# Compare the time taken to multiply two Python lists vs. two NumPy arrays.
#by using python list
import time
l1 = [1, 2, 3]
l2 = [4, 5, 6]
start = time.time()
multiply = [x*y for x,y in zip(l1, l2)]
end = time.time()
print(multiply)
print(end - start)

[4, 10, 18]
0.0


In [36]:
# by using numpy array
l1 = np.array([1, 2, 3])
l2 = np.array([4, 5, 6])
start = time.time()
multiply =l1 * l2
end = time.time()
print(multiply)
print(end - start)

[ 4 10 18]
0.0


In [37]:
# Find the memory size of a NumPy array with 1 million elements.
import sys

list_data = list(range(1_000_000))
numpy_data = np.array(list_data)

print("Python list size:", sys.getsizeof(list_data) * len(list_data), "bytes")
print("NumPy array size:", numpy_data.nbytes, "bytes")

Python list size: 8000056000000 bytes
NumPy array size: 4000000 bytes
